using MedApp.Data;
using MedApp.Models;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace MedApp.Services;

public class ReportService
{
    private readonly MedicationRepository _medRepo;
    private readonly DoseLogRepository _logRepo;

    public ReportService(MedicationRepository medRepo, DoseLogRepository logRepo)
    {
        _medRepo = medRepo;
        _logRepo = logRepo;
    }

    /// <summary>Build report data for a single day.</summary>
    public async Task<ReportData> GetDailyReportAsync(DateTime date)
    {
        return await BuildReportAsync(date.Date, date.Date.AddDays(1), isWeekly: false)
            .ConfigureAwait(false);
    }

    /// <summary>Build report data for the 7-day week starting at weekStart.</summary>
    public async Task<ReportData> GetWeeklyReportAsync(DateTime weekStart)
    {
        return await BuildReportAsync(weekStart.Date, weekStart.Date.AddDays(7), isWeekly: true)
            .ConfigureAwait(false);
    }

    /// <summary>Generate a PDF file from report data and return the file path.</summary>
    public string GeneratePdf(ReportData data)
    {
        QuestPDF.Settings.License = LicenseType.Community;

        var fileName = $"MedApp_Report_{data.StartDate:yyyyMMdd}.pdf";
        var filePath = Path.Combine(FileSystem.CacheDirectory, fileName);

        var periodLabel = data.IsWeekly
            ? $"{data.StartDate:MMM d} – {data.EndDate.AddDays(-1):MMM d, yyyy}"
            : $"{data.StartDate:MMMM d, yyyy}";

        Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(40);

                page.Header().Text($"MedApp — {(data.IsWeekly ? "Weekly" : "Daily")} Report")
                    .FontSize(20).Bold().FontColor(QuestPDF.Helpers.Colors.Blue.Darken3);

                page.Content().Column(col =>
                {
                    col.Spacing(12);

                    col.Item().Text(periodLabel).FontSize(14);

                    // Summary
                    col.Item().Table(table =>
                    {
                        table.ColumnsDefinition(c =>
                        {
                            c.RelativeColumn(); c.RelativeColumn();
                            c.RelativeColumn(); c.RelativeColumn();
                        });

                        table.Header(h =>
                        {
                            h.Cell().Text("Total").Bold();
                            h.Cell().Text("Taken").Bold();
                            h.Cell().Text("Missed").Bold();
                            h.Cell().Text("Adherence").Bold();
                        });

                        table.Cell().Text($"{data.TotalDoses}");
                        table.Cell().Text($"{data.TakenCount}");
                        table.Cell().Text($"{data.MissedCount}");
                        table.Cell().Text($"{data.AdherencePercent}%");
                    });

                    // Per-medication breakdown
                    col.Item().Text("Per Medication").FontSize(16).Bold();

                    col.Item().Table(table =>
                    {
                        table.ColumnsDefinition(c =>
                        {
                            c.RelativeColumn(3); c.RelativeColumn();
                            c.RelativeColumn(); c.RelativeColumn();
                            c.RelativeColumn();
                        });

                        table.Header(h =>
                        {
                            h.Cell().Text("Medication").Bold();
                            h.Cell().Text("Taken").Bold();
                            h.Cell().Text("Missed").Bold();
                            h.Cell().Text("Skipped").Bold();
                            h.Cell().Text("Adherence").Bold();
                        });

                        foreach (var line in data.Medications)
                        {
                            table.Cell().Text(line.MedicationName);
                            table.Cell().Text($"{line.Taken}");
                            table.Cell().Text($"{line.Missed}");
                            table.Cell().Text($"{line.Skipped}");
                            table.Cell().Text($"{line.AdherencePercent}%");
                        }
                    });
                });

                page.Footer().AlignCenter()
                    .Text($"Generated by MedApp on {DateTime.Now:g}").FontSize(9);
            });
        }).GeneratePdf(filePath);

        return filePath;
    }

    // ── Private ──────────────────────────────────────────────────────────────

    private async Task<ReportData> BuildReportAsync(DateTime start, DateTime end, bool isWeekly)
    {
        var logs = await _logRepo.GetByDateRangeAsync(start, end).ConfigureAwait(false);
        var schedules = await _medRepo.GetAllActiveSchedulesAsync().ConfigureAwait(false);

        // Build schedule → medication lookup
        var medCache = new Dictionary<int, Medication>();
        var scheduleToMed = new Dictionary<int, Medication>();
        foreach (var s in schedules)
        {
            if (!medCache.TryGetValue(s.MedicationId, out var med))
            {
                med = await _medRepo.GetByIdAsync(s.MedicationId).ConfigureAwait(false);
                if (med is not null) medCache[s.MedicationId] = med;
            }
            if (med is not null)
                scheduleToMed[s.Id] = med;
        }

        // Group by medication
        var grouped = new Dictionary<string, MedicationReportLine>();
        foreach (var log in logs)
        {
            var medName = scheduleToMed.TryGetValue(log.ScheduleId, out var med)
                ? med.Name : "Unknown";

            if (!grouped.TryGetValue(medName, out var line))
            {
                line = new MedicationReportLine { MedicationName = medName };
                grouped[medName] = line;
            }

            switch (log.Status)
            {
                case DoseStatus.Taken:   line.Taken++;   break;
                case DoseStatus.Missed:  line.Missed++;  break;
                case DoseStatus.Skipped: line.Skipped++; break;
            }
        }

        var report = new ReportData
        {
            StartDate = start,
            EndDate = end,
            IsWeekly = isWeekly,
            TotalDoses = logs.Count,
            TakenCount = logs.Count(l => l.Status == DoseStatus.Taken),
            MissedCount = logs.Count(l => l.Status == DoseStatus.Missed),
            SkippedCount = logs.Count(l => l.Status == DoseStatus.Skipped),
            Medications = grouped.Values.OrderBy(l => l.MedicationName).ToList()
        };

        return report;
    }
}
